### ISSUE TITLE
Footer Implementation with Get in Touch, Follow Us, Sign Up to Newsletter, and Our Office Sections

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#100]
### Acceptance Criteria
Given all the users, everyone should be able to access and interact with the footer sections seamlessly.

### Performance Criteria
The "Performance Criteria” establishes the system’s performance expectations.
- [ ] The footer should load fast.
- [ ] Interaction with the "Sign Up to Newsletter" form should be responsive.

### Footer Components
1. **"Get in Touch" Section**
    - [ ] Add a "Get in Touch" section in the footer.
    - [ ] Include the email address "daedalusdev@gmail.com."

2. **"Follow Us" Section**
    - [ ] Create a "Follow Us" section in the footer.
    - [ ] Add social media icons (Twitter, Facebook, Discord, LinkedIn).
    - [ ] Link each social media icon to its corresponding profile.

3. **"Sign Up to Newsletter" Section**
    - [ ] Implement a "Sign Up to Newsletter" section in the footer.
    - [ ] Include an input field for the email address.
    - [ ] Add a submit button.
    - [ ] Ensure the form is functional.

4. **"Our Office" Section**
    - [ ] Include an "Our Office" section in the footer.
    - [ ] Specify the location as "Metro Manila."

### Definition of Ready
The "Definition of Ready” means that stories must be immediately actionable.
- [ ] Has acceptance criteria.
- [ ] Has the appropriate labels.
- [ ] Has a testable criteria.
- [ ] Has steps that need to be completed.

### Definition of Done
The "Definition of Done” is when it meets all the criteria and delivers the desired functionality, then it is considered 'done'.
- [ ] All tests (old and new) have passed.
- [ ] All old tests have been removed.
- [ ] Updated or added features to the documentation.

### Additional Notes:
- Refer to the figma design prototype, click [here](https://www.figma.com/file/cD2fw45bSKLzqdr3jmjOdl/Landing-Page-v.1?type=design&node-id=1-1199&mode=design&t=OFmS5OihXHM5AEdZ-0).
- If you have any questions or need clarification, feel free to ask.

**Comment by Frostzeichen** [comment]
@os-hi can I work on this?

**Comment by os-hi** [comment]
@Frostzeichen  yeah sure, just assign urself

**Comment by Frostzeichen** [comment]
@os-hi Does the "subscribe to newsletter" function have a backend API now? Where should I send the form data?

**Comment by os-hi** [comment]
@directormac  si mac nakakaalam pre
