### ISSUE TITLE
Home Page sections and components

### ISSUE THREAD

**Issue by devpapi0891** [daedalus-developers/daedalus.codes#117]

**Comment by erikachenchan** [comment]
May I ask what's this about? So I can set a milestone for this task. Thank you

**Comment by devpapi0891** [comment]
It is to create components for index page. Right now all data like in Team section are just static. We still need to make some of the data dynamic.
![image](https://github.com/daedalus-developers/daedalus.codes/assets/97945953/adb3dd4a-dc4a-4e2b-8013-7eee72a823e7)

**Comment by devpapi0891** [comment]
Made adjustments after the update to Sveltekit 2.0. Also made Events, Projects, and Team components data dynamic and streamed.

**Comment by directormac** [comment]
Close by  #118
