### ISSUE TITLE
Contact Page: Fix light mode text color

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#160]
texts in light mode are not visible. change the text color
![Image](https://github.com/daedalus-developers/daedalus.codes/assets/110341554/3c158ef1-09e0-4a55-becb-611b03daf07a)

**Comment by Frostzeichen** [comment]
@os-hi can I try my hand on this?

**Comment by os-hi** [comment]
yess @Frostzeichen
