### ISSUE TITLE
Color Schemes & Logo

### ISSUE THREAD

**Issue by daedalusdevph** [daedalus-developers/daedalus.codes#2]
# Discuss Color Schemes and Global Styles

**Comment by daedalusdevph** [comment]
Add figma designs here and assets to consider

**Comment by wilmer162000** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/0c1e5c57-5703-4bb1-ae72-a58c43d53387)

**Comment by daedalusdevph** [comment]
> ![image](https://user-images.githubusercontent.com/140242655/267410625-0c1e5c57-5703-4bb1-ae72-a58c43d53387.png)

# 1 Prosoal, Please define set of color schemes.

**Comment by wilmer162000** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/35bcd341-2faf-4fe0-ae26-913d91aa5a35)
sample color schemes

**Comment by wilmer162000** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/f19c7855-9e3f-45c7-b47b-13d232393ff8)

**Comment by wilmer162000** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/59f4a904-b88b-43b0-9720-1faa58c1458d)
MAY FOOTER DIN TO FOR CONTACT AND OTHER INFOS LIKE PARTNERSHIP, tech stacks, ROADMAP PREVIEW..  btw This is just an example from my other projects..

**Comment by daedalusdevph** [comment]
Please split the images into smaller pieces or edit it as this

```html
<img src="origlink from hub> alt="adsfdsaf> width="100px" height="100px" />
```

@wilmer162000 Thanks Para readable ung thread.

**Comment by wilmer162000** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/e95510d1-44e0-4503-a0f1-5a562a478811

**Comment by wilmer162000** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/921a0c9a-ffc2-429c-9413-e44097137a94)

**Comment by wilmer162000** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/9ebd5775-1d85-4707-953c-06dc821d28a3)

**Comment by wilmer162000** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/39e22603-0278-4ec0-a97c-e1b0b1257b82)

**Comment by wilmer162000** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/aef74cac-3bf8-4782-9cc7-cabffda997e6)

**Comment by wilmer162000** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/43590068-73b2-4fea-8dcd-07ad19b81bca)

**Comment by wilmer162000** [comment]
![image 2](https://github.com/daedalus-developers/daedalus.codes/assets/140242655/3de2afeb-6f89-40f1-ba64-7bd8fdefd5fd)

the project odin as reference ko sa page minsan, since nag o-offer din sila ng courses for public

**Comment by directormac** [comment]
Hello For Reference regarding the logo and the column part

1. On wide screens we should limit the container so it wont look too apart
2. Still I am voting for a no logo, A simeple D or a word like DAEDALUS like what render has looks sexy  a reference below is given.

Again it cringes me that the temporary logo looks like one that i dont want to mention, 
Thank you. Hope you consider


![image](https://github.com/daedalus-developers/daedalus.codes/assets/5866196/36d57f16-6c30-4cdc-8ef4-bf5af386ad19)
