### ISSUE TITLE
CourseProject Section Component

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#33]
Please visit frontendmentor.io for reference. You may also decide for the design yourself.
Use CourseProject.svelte as the name of the component

![Image](https://github.com/daedalus-developers/daedalus.codes/assets/110341554/5fb0a591-2d9e-46c8-8e37-dee53d75daa6)

**Comment by DDuran19** [comment]
Done doing the sidebar component with hover effects.

![image](https://github.com/daedalus-developers/daedalus.codes/assets/128191960/e07cc39c-6175-4d5c-86cc-d85ff00cfeca)
![image](https://github.com/daedalus-developers/daedalus.codes/assets/128191960/9d950e00-95c8-4854-b348-5b82458e3997)

**Comment by DDuran19** [comment]
done with the course content container including the cards with some hover effects consistent to the card on the landing page.
The data expected is courses[]:

```ts
interface courses{
    title: string;
    shortDescription: string;
    backgroundImage: string;
}
```

![image](https://github.com/daedalus-developers/daedalus.codes/assets/128191960/5a934b53-fdde-4dce-8b81-a9d7e0e58cb2)
