### ISSUE TITLE
Change the Course Cards

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#38]
Can we change these cards
![Image](https://github.com/daedalus-developers/daedalus.codes/assets/110341554/73d85e86-ab2e-418a-bbe9-12507139c1ba)

into something like this? and instead of "lifetime" sa center, change it into "Free" then we can use the same amount in the monthly and yearly.

![Image](https://github.com/daedalus-developers/daedalus.codes/assets/110341554/939ed597-686a-4797-a3b3-fb8b430dca50)

**Comment by os-hi** [comment]
@boosquack  pa lead ako dito pre

**Comment by boosquack** [comment]
### UI : Subscription Cards
@os-hi  here is the first draft for issue #38: Change the Course Cards

![Screenshot (242)](https://github.com/daedalus-developers/daedalus.codes/assets/127096823/57721c06-330f-419c-9788-b1206d12c6e6)

**Comment by os-hi** [comment]
i-highlight mo yung patok na course option, say yung free yung usually mabenta. you can do it by adding a gold border or anything you prefer.
