### ISSUE TITLE
Consider resolution larger than 1080

### ISSUE THREAD

**Issue by devpapi0891** [daedalus-developers/daedalus.codes#39]
- The website may generate excessive white space on the left and right sides of the screen when viewed on resolutions greater than 1080.
- Not so sure but it might look like the example below:
![image](https://github.com/daedalus-developers/daedalus.codes/assets/97945953/5a6e45d9-d61d-4c97-a183-6c16733a4b67)

- Should we consider using a standard container class like .container in Tailwind CSS? Currently, we are using something like .mx-auto .max-w-7xl.

**Comment by directormac** [comment]
![image](https://github.com/daedalus-developers/daedalus.codes/assets/5866196/8af067dc-ee95-44b8-83c1-56b01484cce3)
Using 1440p

Suggestions are good, was just rapidly developing the app and used max-w-7xl all the way.

**Comment by DDuran19** [comment]
What's the status with this and how should we move forward? @daedalus-developers/ui-ux  team, what are your thoughts about this

**Comment by directormac** [comment]
Follow up on this please also relates to #49
