### ISSUE TITLE
smallest screen mobile responsiveness

### ISSUE THREAD

**Issue by DDuran19** [daedalus-developers/daedalus.codes#46]
There's an extra space at the right side of the screen **probably** caused by "For Upskilling" card
width - 320px

![Image](https://github.com/daedalus-developers/daedalus.codes/assets/128191960/299d9ea7-66ba-4a52-b49e-2d7a2704c95d)

![Image](https://github.com/daedalus-developers/daedalus.codes/assets/128191960/33611ee2-ac35-4246-a377-a864b3d9496a)

**Comment by directormac** [comment]
We checked this earlier and was addressed by  issue #36 was merged  at #43. 
Please re check founder @os-hi
