### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by DDuran19** [daedalus-developers/daedalus.codes#48]
Can we make the navbar sticky? so it flushes to top without the awkward margin at top when in the middle of the page
Find a fix for the overflowing blur effect on both sides.

- [ ] fix navbar position (should be sticky)
- [ ] fix overflow blur on both sides of x-axis

![Image](https://github.com/daedalus-developers/daedalus.codes/assets/128191960/6e730dc9-3f1c-4e5e-97f7-1dbf5d563f47)

![Image](https://github.com/daedalus-developers/daedalus.codes/assets/128191960/0143fe58-db28-475d-91e5-01f7c2b35618)

**Comment by directormac** [comment]
Please respond to this issue @boosquack  @wilmer162000

**Comment by boosquack** [comment]
noted will be doing this ASAP

**Comment by DDuran19** [comment]
This has been fixed already
