### ISSUE TITLE
Change Contact Info

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#57]
Please update the contact info on the footer section

for contact info:
Email Address: daedalusdevph@gmail.com
Contact Number: (+63) 9564261438

to add:
-[] Discord icon, link: https://discord.gg/daedalusdev
-[] YouTube icon, link: https://www.youtube.com/@DaedalusDevelopers

to fix:
-[] Email Address
-[] Contact Number
-[] Tiktok link: https://www.tiktok.com/@daedalusdev
-[] Twitter link: https://twitter.com/DaedalusDevPH
-[] LinkedIn link: https://www.linkedin.com/in/daedalus-community-94ba51292/

to edit:
-[] Philippine flag must be aligned to the "Philippines" word
-[] Social icons must have the same width and height 

![Image](https://github.com/daedalus-developers/daedalus.codes/assets/110341554/ebe3b465-410f-488b-a51e-1a2cec4c029b)

**Comment by toney010319** [comment]
[] Social icons must have the same width and height

upon checking the width and height of the icon it is in the same size po.

**Comment by os-hi** [comment]
okay noted. also, please add the linkedin icon as well as the link of our daedalus linkedin page : https://www.linkedin.com/company/daedalusdev 

thank you
