### ISSUE TITLE
fix: social links alignment on mobile

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#74]
please align the social link icons as well the top margin of  "get our infographics"

![Image](https://github.com/daedalus-developers/daedalus.codes/assets/110341554/c0d56daf-7f07-4008-89cd-cf64f50f05f5)

**Comment by directormac** [comment]
Please refer to #72 i believe this was addressed on the PR

**Comment by os-hi** [comment]
i see, what do i do with this issue? should i delete it?

**Comment by os-hi** [comment]
if you meant the social icon links below, centered is fine. However, I see that the texts above aren't aligned, can we fix this instead?

![Image](https://github.com/daedalus-developers/daedalus.codes/assets/110341554/c64de98f-bb61-4641-b1e0-d30069883e0b)
