### ISSUE TITLE
Create Register page

### ISSUE THREAD

**Issue by DDuran19** [daedalus-developers/daedalus.codes#86]
- [ ] /register
- [ ] username
- [ ] email
- [ ] firstName
- [ ] lastName
- [ ] discordUsername
- [ ] tier (freemium, pro) defaulted to freemium
- [ ] phoneNumber
- [ ] facebookProfile
- [ ] githubProfile
- [ ] displayPicture
- [ ] active(not shown, default to true)

**Comment by Frostzeichen** [comment]
- [x]  /register
- [ ] username
- [ ] email
- [ ] firstName
- [ ] lastName
- [ ] discordUsername
- [ ] tier (freemium, pro) defaulted to freemium
- [ ] phoneNumber
- [ ] facebookProfile
- [ ] githubProfile
- [ ] displayPicture
- [ ] active(not shown, default to true)

**Comment by Frostzeichen** [comment]
PR sent!
