### ISSUE TITLE
Reiteration: PHASE 1

### ISSUE THREAD

**Issue by directormac** [daedalus-developers/daedalus.codes#93]
- [x] Authentication 

Please put here the best features of your voting system that we can integrate.

**Comment by Frostzeichen** [comment]
> Please put here the best features of your voting system that we can integrate.
I'd say, that would be the database for my team. But that's because I mainly worked on the voting system and not much on the UI. We could add the countdown timer too btw. Right @Manggigi?

**Comment by Manggigi** [comment]
> > Please put here the best features of your voting system that we can integrate.
> I'd say, that would be the database for my team. But that's because I mainly worked on the voting system and not much on the UI. We could add the countdown timer too btw. Right @Manggigi?

Yes, the whole page where the countdown is shown looks cool. Additionally, we implemented a skeleton component state to handle loading data. Abused server load and server actions.

**Comment by directormac** [comment]
Lets settle with the user information what are the fields wed want to store not not want to store
