### ISSUE TITLE
Header Implementation with Logo, Navigation Bar, Courses, Contact, Search Icon, Login Button, and Dark/Light Mode

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#94]
### Acceptance Criteria
Given all the users, everyone should be able to interact with the header components seamlessly.

### Performance Criteria
The "Performance Criteria” establishes the system’s performance expectations.
- The data should load fast.
- Fetching data should not be slow.

### Header Components
1. **Logo and Navigation Bar**
    - [x] Integrate a logo into the header.
    - [x] Implement a responsive navigation bar with the following sections:
        - [x] About
        - [x] Portfolio
        - [x] Team
        - [x] Events

2. **Courses**
    - [x] Include a section for courses in the header.
    - [x] Ensure the courses section is easily accessible.

3. **Contact**
    - [x] Add a contact link in the header.
    - [x] Make sure the contact link is prominently displayed.

4. **Search Icon**
    - [x] Integrate a search icon into the header.
    - [x] Implement search functionality or link it to the relevant search page.

5. **Login Button**
    - [x] Create a login button in the header.
    - [x] Ensure the login button is functional and leads to the login page.

6. **Dark/Light Mode**
    - [x] Implement a toggle for dark/light mode in the header.
    - [x] Ensure the theme changes seamlessly.

### Definition of Ready
The "Definition of Ready” means that stories must be immediately actionable.
- [x] Has acceptance criteria.
- [x] Has the appropriate labels.
- [x] Has a testable criteria.
- [x] Has steps that need to be completed.

### Definition of Done
The "Definition of Done” is when it meets all the criteria and delivers the desired functionality, then it is considered 'done'.
- [x] All tests (old and new) have passed.
- [x] All old tests have been removed.
- [x] Updated or added features to the documentation.

### Additional Notes:
- Refer to the figma design prototype, click [here](https://www.figma.com/file/cD2fw45bSKLzqdr3jmjOdl/Landing-Page-v.1?type=design&node-id=1-1199&mode=design&t=OFmS5OihXHM5AEdZ-0).
- If you have any questions or need clarification, feel free to ask.

**Comment by erikachenchan** [comment]
I suppose this is already finished? Don't forget to tick all the boxes and close this issue. @devpapi0891

**Comment by devpapi0891** [comment]
Yes. Sorry for the late response.  Also I cant click the checkboxes.

![image](https://github.com/daedalus-developers/daedalus.codes/assets/97945953/16f633b1-2174-42a0-a057-a2d7c265a02e)
![image](https://github.com/daedalus-developers/daedalus.codes/assets/97945953/6c32de4d-f57e-46f5-9713-129297b0c46a)
