### ISSUE TITLE
About Page Implementation with Carousel, Connect, Browse Free Courses, and Mentorship Sections

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#96]
### Acceptance Criteria
Given all the users, everyone should be able to navigate to the About page and interact with the carousel, "Connect," "Browse Free Courses," and "Mentorship" sections seamlessly.

### Performance Criteria
The "Performance Criteria” establishes the system’s performance expectations.
- The About page should load fast.
- Fetching data for the carousel, "Connect," "Browse Free Courses," and "Mentorship" sections should not be slow.

### About Page Components
1. **Carousel for Mission and Vision**
    - [ ] Implement a carousel for the mission and vision on the About page.
    - [ ] Ensure the carousel transitions smoothly between different mission and vision statements.

2. **Connect Section**
    - [ ] Create a "Connect" section on the About page.
    - [ ] Add a link to the Discord server for users to connect.
    - [ ] Verify that the link redirects users to the Discord server.

3. **Browse Free Courses Section**
    - [ ] Include a "Browse Free Courses" section on the About page.
    - [ ] Add a link to the /courses page.
    - [ ] Verify that the link directs users to the /courses page.

4. **Mentorship Section**
    - [ ] Integrate a "Mentorship" section on the About page.
    - [ ] Add a link to the mentorship registration page.
    - [ ] Verify that the link redirects users to the mentorship registration page.

### Definition of Ready
The "Definition of Ready” means that stories must be immediately actionable.
- [ ] Has acceptance criteria.
- [ ] Has the appropriate labels.
- [ ] Has a testable criteria.
- [ ] Has steps that need to be completed.

### Definition of Done
The "Definition of Done” is when it meets all the criteria and delivers the desired functionality, then it is considered 'done'.
- [ ] All tests (old and new) have passed.
- [ ] All old tests have been removed.
- [ ] Updated or added features to the documentation.

### Additional Notes:
- Discord link is : https://discord.gg/daedalusdev
- Refer to the figma design prototype, click [here](https://www.figma.com/file/cD2fw45bSKLzqdr3jmjOdl/Landing-Page-v.1?type=design&node-id=1-1199&mode=design&t=OFmS5OihXHM5AEdZ-0).
- If you have any questions or need clarification, feel free to ask.

**Comment by DDuran19** [comment]
Hi @os-hi  I am getting an error, can you assist me? Sorry I was left out and needs some help catching up

here are the errors I am getting when running `pnpm run dev`

```sh
$ pnpm dev

> daedalus.codes@0.0.1 dev F:\PC-Libraries\Documents\Coding\DaedalusDevelopers\daedalus.codes
> pnpm run dev:api & pnpm run dev:web


> daedalus.codes@0.0.1 dev:api F:\PC-Libraries\Documents\Coding\DaedalusDevelopers\daedalus.codes
> node -e "const exec = process.platform === 'win32' ? 'pocketbase.exe' : 'pocketbase'; require('child_process').execFileSync('./pb/' + exec, ['serve'], { stdio: 'inherit' })"

<ref *1> node:child_process:929
    throw err;
    ^

Error: spawnSync ./pb/pocketbase.exe ENOENT
    at Object.spawnSync (node:internal/child_process:1117:20)
    at spawnSync (node:child_process:876:24)
    at Object.execFileSync (node:child_process:919:15)
    at [eval]:1:103
    at Script.runInThisContext (node:vm:123:12)
    at Object.runInThisContext (node:vm:299:38)
    at node:internal/process/execution:82:21
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:81:62)
    at evalScript (node:internal/process/execution:103:10) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync ./pb/pocketbase.exe',
  path: './pb/pocketbase.exe',
  spawnargs: [ 'serve' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}

Node.js v18.18.0
 ELIFECYCLE  Command failed with exit code 1.

> daedalus.codes@0.0.1 dev:web F:\PC-Libraries\Documents\Coding\DaedalusDevelopers\daedalus.codes
> vite dev --host

'vite' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by DDuran19** [comment]
Also, I don't see the "About" section on the figma in the given link

**Comment by os-hi** [comment]
i think you need to run the pb locally @DDuran19

**Comment by os-hi** [comment]
the about section is this 
![image](https://github.com/daedalus-developers/daedalus.codes/assets/110341554/4c8621c2-98d8-4269-b1ff-f70875abc0ff)

**Comment by erikachenchan** [comment]
@os-hi @DDuran19 is this done?

**Comment by DDuran19** [comment]
> i think you need to run the pb locally @DDuran19

Can you help me set it up? 
so the about page is not /about but instead will just be About.svelte that will be used by the homepage?

**Comment by os-hi** [comment]
@DDuran19  yes suree. however, in case im not available, you can follow the guideline on README.md. it should help you set up your pocketbase locally. and yes, the about page is not /about but About.svelte instead
