### ISSUE TITLE
Portfolio Page Implementation with Project Cards

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#97]
### Acceptance Criteria
Given all the users, everyone should be able to navigate to the Portfolio page and view project cards seamlessly.

### Performance Criteria
The "Performance Criteria” establishes the system’s performance expectations.
- The Portfolio page should load fast.
- Fetching data for project cards should not be slow.

### Portfolio Page Components
1. **Project Cards**
    - [x] Design and implement project cards on the Portfolio page.
    - [x] Each card should include:
        - [x] A banner/picture representing the project.
        - [x] Industry type (e.g., blockchain, food).
        - [x] Project title.
        - [x] Project description.

2. **Card Styling**
    - [x] Ensure consistent styling for project cards.
    - [x] Test the responsiveness of project cards on various devices.

### Definition of Ready
The "Definition of Ready” means that stories must be immediately actionable.
- [x] Has acceptance criteria.
- [x] Has the appropriate labels.
- [x] Has a testable criteria.
- [x] Has steps that need to be completed.

### Definition of Done
The "Definition of Done” is when it meets all the criteria and delivers the desired functionality, then it is considered 'done'.
- [x] All tests (old and new) have passed.
- [x] All old tests have been removed.
- [x] Updated or added features to the documentation.

### Additional Notes:
- Refer to the figma design prototype, click [here](https://www.figma.com/file/cD2fw45bSKLzqdr3jmjOdl/Landing-Page-v.1?type=design&node-id=1-1199&mode=design&t=OFmS5OihXHM5AEdZ-0).
- If you have any questions or need clarification, feel free to ask.

**Comment by erikachenchan** [comment]
Any updates on this ? Don't forget to tick all the boxes and close this issue if you're done @eggzylog
