### ISSUE TITLE
Team Page Implementation with "View All Team" Button and Member Sections

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#98]
### Acceptance Criteria
Given all the users, everyone should be able to navigate to the Team page, view individual team members, and use the "View All Team" button to access the /deadalusteam page seamlessly.

### Performance Criteria
The "Performance Criteria” establishes the system’s performance expectations.
- The Team page should load fast.
- Fetching data for individual team members should not be slow.

### Team Page Components
1. **"View All Team" Button**
    - [x] Create a "View All Team" button on the Team page.
    - [x] Add a link to the /deadalusteam page.
    - [x] Verify that clicking the button redirects users to the /deadalusteam page.

2. **Individual Team Members Sections**
    - [x] Display three sections for individual team members on the Team page.
    - [x] Each section should include:
        - [x] Photo of the team member.
        - [x] Name of the team member.
        - [x] Description of the team member.
        - [x] GitHub icon linked to the team member's GitHub profile.
        - [x] LinkedIn icon linked to the team member's LinkedIn profile.

### Definition of Ready
The "Definition of Ready” means that stories must be immediately actionable.
- [x] Has acceptance criteria.
- [x] Has the appropriate labels.
- [x] Has a testable criteria.
- [x] Has steps that need to be completed.

### Definition of Done
The "Definition of Done” is when it meets all the criteria and delivers the desired functionality, then it is considered 'done'.
- [x] All tests (old and new) have passed.
- [x] All old tests have been removed.
- [x] Updated or added features to the documentation.

### Additional Notes:
- Refer to the figma design prototype, click [here](https://www.figma.com/file/cD2fw45bSKLzqdr3jmjOdl/Landing-Page-v.1?type=design&node-id=1-1199&mode=design&t=OFmS5OihXHM5AEdZ-0).
- If you have any questions or need clarification, feel free to ask.

**Comment by erikachenchan** [comment]
Any updates on this?
