### ISSUE TITLE
Event Page Implementation with Hackathon and Webinar Cards

### ISSUE THREAD

**Issue by os-hi** [daedalus-developers/daedalus.codes#99]
### Acceptance Criteria
Given all the users, everyone should be able to navigate to the Event page, view both hackathon and webinar sections, and interact with event cards seamlessly.

### Performance Criteria
The "Performance Criteria” establishes the system’s performance expectations.
- [x] The Event page should load fast.
- [x] Fetching data for event cards should not be slow.

### Event Page Components
1. **Event Types - Hackathon and Webinar**
    - [x] Create sections for both hackathon and webinar events on the Event page.
    - [x] Ensure the sections are visually distinct and labeled appropriately.

2. **Event Cards**
    - [x] Design and implement event cards for both hackathon and webinar events.
    - [x] Each card should include:
        - [x] Banner representing the event.
        - [x] Title of the event.
        - [x] Description of the event.
        - [x] Date of the event.
        - [x] Time of the event.

### Definition of Ready
The "Definition of Ready” means that stories must be immediately actionable.
- [x] Has acceptance criteria.
- [x] Has the appropriate labels.
- [x] Has a testable criteria.
- [x] Has steps that need to be completed.

### Definition of Done
The "Definition of Done” is when it meets all the criteria and delivers the desired functionality, then it is considered 'done'.
- [ ] All tests (old and new) have passed.
- [ ] All old tests have been removed.
- [ ] Updated or added features to the documentation.

### Additional Notes:
- Refer to the figma design prototype, click [here](https://www.figma.com/file/cD2fw45bSKLzqdr3jmjOdl/Landing-Page-v.1?type=design&node-id=1-1199&mode=design&t=OFmS5OihXHM5AEdZ-0).
- If you have any questions or need clarification, feel free to ask.

**Comment by erikachenchan** [comment]
Hi @hannie404 any updates on this?

**Comment by hannie404** [comment]
> Hi @hannie404 any updates on this?

I have already fixed the responsiveness of the event cards ma'am. What's left to be done is to make the cards dynamic since it's currently static.

**Comment by directormac** [comment]
made dynamic by #159

**Comment by directormac** [comment]
Filterable and pagination enabled by #168

**Comment by erikachenchan** [comment]
Is this already implemented?

**Comment by erikachenchan** [comment]
@devpapi0891 @directormac

**Comment by directormac** [comment]
closed by #174
